### ISSUE TITLE
Please Update LaunchDarkly and Gatsby versions.

### ISSUE THREAD

**Issue by TwisterMc** [launchdarkly/gatsby-plugin-launchdarkly#33]
Please support LaunchDarkly React SDK 3.0.x https://github.com/launchdarkly/react-client-sdk

Please support Gatsby 5.x https://changelog.gatsbyjs.io

**Comment by yusinto** [comment]
This has been resolved in [v1.0](https://github.com/launchdarkly/gatsby-plugin-launchdarkly/releases).
